export const HEADER =
  '# Generated by tools/generate-redirects.mjs from deploy/legacy-urls.csv — do not edit';

const LOCALE_PREFIX = '/en';

export const parseCsv = text => {
  const [header, ...lines] = text.trim().split('\n');
  const columns = header.split(',');

  return lines.map(line => {
    const values = line.split(',');

    return Object.fromEntries(columns.map((column, index) => [column, values[index] ?? '']));
  });
};

// `exact` matches the path with either slash form, `prefix` covers a whole directory, and `regex`
// is written out in the CSV. Every pattern starts with `^/` so the /en/ mirror is one splice.
const pattern = ({ path, match }) => {
  switch (match) {
    case 'exact':
      return `^${path.replace(/\/$/, '')}/?$`;
    case 'prefix':
      return `^${path}`;
    case 'regex':
      return path;
    default:
      throw new Error(`unknown match type "${match}" for ${path}`);
  }
};

const localize = pattern => {
  if (!pattern.startsWith('^/')) {
    throw new Error(`pattern "${pattern}" is not anchored at ^/ and cannot be mirrored into /en/`);
  }

  return `^${LOCALE_PREFIX}${pattern.slice(1)}`;
};

const rule = (status, pattern, target) =>
  target ? `RedirectMatch ${status} ${pattern} ${target}` : `RedirectMatch ${status} ${pattern}`;

export const buildRules = rows =>
  rows.flatMap(row => {
    const source = pattern(row);
    const localizedTarget =
      row.targetScope === 'root' ? row.target : `${LOCALE_PREFIX}${row.target}`;

    return [
      rule(row.status, source, row.target),
      rule(row.status, localize(source), row.target ? localizedTarget : ''),
    ];
  });

export const buildRedirectsFile = rows => `${[HEADER, '', ...buildRules(rows)].join('\n')}\n`;
