name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://boundfoxstudios.com
    steps:
      - uses: actions/checkout@v7
        with:
          ref: main
      - uses: ./.github/actions/read-node-version-from-nvmrc
        id: node-version
      - uses: ./.github/actions/prepare-node
        with:
          version: ${{ steps.node-version.outputs.version }}
      - run: npm run fetch:github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx ng build
      - run: npm run postbuild
      - name: Upload assets
        uses: SamKirkland/FTP-Deploy-Action@110f9186c050f71550953127052e77650219c287 # v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: dist/website/browser/
          server-dir: /
          state-name: .ftp-deploy-sync-state.assets.json
          log-level: minimal
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/*.html
      - name: Upload documents
        uses: SamKirkland/FTP-Deploy-Action@110f9186c050f71550953127052e77650219c287 # v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: dist/website/browser/
          server-dir: /
          state-name: .ftp-deploy-sync-state.html.json
          log-level: minimal
